### ISSUE TITLE
BUG: pre-commit error caused by sdist

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#512]
### Bug description

Running pre-commit hooks produces the error `ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist`.

I get the same error when running `conda env update -f .\environment.yml`.

<details>
<summary>full traceback</summary>

``````

['C:\\Users\\Christian Zimpelmann\\.cache\\pre-commit\\repoz9ro7yhz\\py_env-python3\\Scripts\\python.EXE', '-m', 'build', '--sdist', '.', '--outdir', 'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\check-manifest-p_9ma3iq-sdist', '--no-isolation'] failed (status 1):
* Getting build dependencies for sdist...

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\version.py:84: UserWarning: tag 'v.0.6.0-alpha.1' no version found
  warnings.warn(f"tag {tag!r} no version found")
Traceback (most recent call last):
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\pep517\in_process\_in_process.py", line 351, in <module>
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\pep517\in_process\_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\pep517\in_process\_in_process.py", line 285, in get_requires_for_build_sdist
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\dist.py", line 475, in __init__
    _Distribution.__init__(
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
    self.finalize_options()
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools\dist.py", line 899, in finalize_options
    ep(self)
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\integration.py", line 127, in infer_version
    _assign_version(dist, config)
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\integration.py", line 60, in _assign_version
    maybe_version = _get_version(config)
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\__init__.py", line 153, in _get_version
    parsed_version = _do_parse(config)
                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\__init__.py", line 100, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\_entrypoints.py", line 66, in _version_from_entrypoints
    version: ScmVersion | None = _call_entrypoint_fn(root, config, ep.load())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\_entrypoints.py", line 40, in _call_entrypoint_fn
    return fn(root, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\git.py", line 181, in parse
    return _git_parse_inner(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\git.py", line 224, in _git_parse_inner
    return meta(
           ^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\version.py", line 226, in meta
    parsed_version = _parse_tag(tag, preformatted, config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Christian Zimpelmann\.cache\pre-commit\repoz9ro7yhz\py_env-python3\Lib\site-packages\setuptools_scm\version.py", line 203, in _parse_tag
    assert version is not None
AssertionError

``````

</details>

**Comment by ChristianZimpelmann** [comment]
`git pull --tags` did not solve the problem.

**Comment by hmgaudecker** [comment]
Ah, I had erroneously set a tag on `v.0.6.0-alpha.1` instead of `v0.6.0-alpha.1` (note the `v.`) at some point and deleted the tag again, looks like that is causing problems.

Try

```
git tag -d v.0.6.0-alpha.1
```

**Comment by ChristianZimpelmann** [comment]
That solved it. Thanks!
