### ISSUE TITLE
Missing pytest dependency in conda package

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#71]
### Bug description

GETTSIM's conda package is missing the dependency on pytest

### To Reproduce

```
$ conda create -n tmp
$ conda activate tmp
$ conda install -c gettsim gettsim
$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gettsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/miniconda3/envs/gst/lib/python3.7/site-packages/gettsim/__init__.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by hmgaudecker** [comment]
Fixed in #70.
